name: Push Check

on: [push, pull_request]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: typos-action
        uses: crate-ci/typos@v1.14.3
  format:
    runs-on: [ self-hosted, X64 ]
    steps:
      - uses: actions/checkout@v3
  
      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@v2.6.2